# Generated by Django 5.2.8 on 2025-11-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del recuerdo')),
                ('descripcion', models.TextField(verbose_name='Carta o Descripción')),
                ('foto', models.ImageField(upload_to='recuerdos/', verbose_name='Foto de nosotros')),
                ('fecha', models.DateField(verbose_name='Fecha del recuerdo')),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Nuestros Momentos',
                'ordering': ['fecha'],
            },
        ),
    ]
