# Generated by Django 5.2.8 on 2025-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='momento',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video (Opcional)'),
        ),
        migrations.AlterField(
            model_name='momento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recuerdos/', verbose_name='Foto'),
        ),
    ]
