# Generated by Django 5.2.8 on 2025-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0002_momento_video_alter_momento_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título de la canción')),
                ('archivo', models.FileField(upload_to='musica/', verbose_name='Archivo de Audio')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Lista de Música',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
