# Generated by Django 5.2.8 on 2025-11-21 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_cancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='momento',
            name='foto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='momento',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
