# Generated by Django 5.2.8 on 2025-12-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0004_alter_cancion_archivo_alter_momento_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('cumplido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
