# Generated by Django 5.2.8 on 2025-12-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0005_deseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Pochita', max_length=50)),
                ('hambre', models.IntegerField(default=100)),
                ('felicidad', models.IntegerField(default=100)),
                ('energia', models.IntegerField(default=100)),
                ('higiene', models.IntegerField(default=100)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Nuestra Mascota',
            },
        ),
    ]
